### ISSUE TITLE
Permission denied when Docker attempts to copy closure-util library

### ISSUE THREAD

**Issue by thomasgwatson** [openlayers/closure-util#257]
Permission denied:

```docker-compose build app
Building app
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "compose/cli/main.py", line 62, in main
  File "compose/cli/main.py", line 114, in perform_command
  File "compose/cli/main.py", line 220, in build
  File "compose/project.py", line 300, in build
  File "compose/service.py", line 727, in build
  File "site-packages/docker/api/build.py", line 55, in build
  File "site-packages/docker/utils/utils.py", line 95, in tar
  File "tarfile.py", line 2013, in add
IOError: [Errno 13] Permission denied: '/var/lib/jenkins-slave/workspace/OUR_APP_NAME/node_modules/closure-util/.deps/compiler/e9db3081300ea6a27d1b6926d843182038111076/COPYING'
docker-compose returned -1
make: *** [run_all_in_docker] Error 255```

Those permissions from a project with Openlayers 3.19.1 and closure_util 1.15.1:
```
-rw-r----- 1 root root 6852340 Nov 22 23:42 compiler.jar
-rw-r----- 1 root root   11358 Nov 22 23:42 COPYING
-rw-r----- 1 root root   13669 Nov 22 23:42 README.md
```

Permissions from a project that builds and has Openlayers 3.12.1 and closure_util 1.9.0
```
-rw-r--r-- 1 root root 6383029 Mar 28  2016 compiler.jar
-rw-r--r-- 1 root root   11358 Mar 28  2016 COPYING
-rw-r--r-- 1 root root   13179 Mar 28  2016 README.md
```

Not sure if this is caused by the precompile step for Openlayers and the closure-util or what...

**Comment by gberaudo** [comment]
These permissions come from the google zip file which is downloaded by closure-util.

**Comment by thomasgwatson** [comment]
So we have to go further upstream to follow this up? :|

**Comment by gberaudo** [comment]
Yes, unless having a workaround in closure-util is OK for its maintainer.
