### ISSUE TITLE
custom builds error

### ISSUE THREAD

**Issue by Leon-001** [openlayers/closure-util#391]
Hi,
I tried to create a custom build, like it is described here:
http://openlayers.org/en/latest/doc/tutorials/custom-builds.html
$ mkdir openlayers
$ npm install openlayers

As result I get this message:
Failed at the closure-util@1.24.0 postinstall script 'node ./bin/closure-util.js update'.
 Make sure you have the latest version of node.js and npm installed.
 If you do, this is most likely a problem with the closure-util package,
 not with npm itself.
 Tell the author that this fails on your system:
     node ./bin/closure-util.js update

I am running this on Linux 4.4.0-97-generic (if this is of any interest).

**Comment by fredj** [comment]
Can you provide your npm and node version?
Do you have additional error message if you install closure-util: `npm install closure-util`

**Comment by fredj** [comment]
are behind a proxy that blocks *.exe download?

**Comment by Leon-001** [comment]
> Can you provide your npm and node version?
  npm: '3.5.2'                                                                                                                                                                                 
  node: '4.2.6'

> Do you have additional error message if you install closure-util: |npm
> install closure-util|
The messages are quite similar. But I have found a little more information in the logfile:

`16002 verbose stack Error: closure-util@1.25.0 postinstall: `node ./bin/closure-util.js update`
16002 verbose stack Exit status 1
16002 verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/lib/utils/lifecycle.js:232:16)
16002 verbose stack     at emitTwo (events.js:87:13)
16002 verbose stack     at EventEmitter.emit (events.js:172:7)
16002 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/lib/utils/spawn.js:24:14)
16002 verbose stack     at emitTwo (events.js:87:13)
16002 verbose stack     at ChildProcess.emit (events.js:172:7)
16002 verbose stack     at maybeClose (internal/child_process.js:821:16)
16002 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
16003 verbose pkgid closure-util@1.25.0
16004 verbose cwd /var/www/fib/openlayers
16005 error Linux 4.4.0-97-generic
16006 error argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "closure-util"
16007 error node v4.2.6
16008 error npm  v3.5.2
16009 error code ELIFECYCLE
16010 error closure-util@1.25.0 postinstall: `node ./bin/closure-util.js update`
16010 error Exit status 1
16011 error Failed at the closure-util@1.25.0 postinstall script 'node ./bin/closure-util.js update'.
16011 error Make sure you have the latest version of node.js and npm installed.
16011 error If you do, this is most likely a problem with the closure-util package,
16011 error not with npm itself.
16011 error Tell the author that this fails on your system:
16011 error     node ./bin/closure-util.js update
16011 error You can get information on how to open an issue for this project with:
16011 error     npm bugs closure-util
16011 error Or if that isn't available, you can get their info via:
16011 error     npm owner ls closure-util
16011 error There is likely additional logging output above.
16012 verbose exit [ 1, true ]`

**Comment by Leon-001** [comment]
> are behind a proxy that blocks *.exe download?

no :)
