### ISSUE TITLE
Closure-Util update failing causing a problem to install

### ISSUE THREAD

**Issue by harinigudipati** [openlayers/closure-util#93]
I am on a Win7 box and my network DOES HAVE A PROXY, but I have HTTP_PROXY and HTTPS_PROXY set. Another little sidenote is our wonderful networking team requires a MITM cert so for npm I need to set...

    export NODE_TLS_REJECT_UNAUTHORIZED="0"

when I run `npm install --verbose closure-utl` I get...

```
 > closure-util@1.10.0 postinstall C:\Users\\tmp\terminal-plus-internal-ui\node_modules\closure-util
> node ./bin/closure-util.js update

info install Downloading http://dl.google.com/closure-compiler/compiler-20151216.zip
info install Downloading https://github.com/google/closure-library/archive/5b25e65.zip
info install Download failed, retrying again in 2s
ERR! closure-util connect ECONNREFUSED
npm verb unsafe-perm in lifecycle true
npm info closure-util@1.10.0 Failed to exec postinstall script
npm verb unlock done using C:\Users\\AppData\Roaming\npm-cache\_locks\closure-util-ad9c4a13fed3733e.lock for C:\Users\\tmp\terminal-plus-internal-ui\node_modules\closure-util
npm verb stack Error: closure-util@1.10.0 postinstall: `node ./bin/closure-util.js update`
npm verb stack Exit status 1
npm verb stack     at EventEmitter.<anonymous> (C:\Users\\AppData\Roaming\nvm\v0.12.4\node_modules\npm\lib\utils\lifecycle.js:213:16)
npm verb stack     at EventEmitter.emit (events.js:110:17)
npm verb stack     at ChildProcess.<anonymous> (C:\Users\\AppData\Roaming\nvm\v0.12.4\node_modules\npm\lib\utils\spawn.js:24:14)
npm verb stack     at ChildProcess.emit (events.js:110:17)
npm verb stack     at maybeClose (child_process.js:1015:16)
npm verb stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
npm verb pkgid closure-util@1.10.0
npm verb cwd C:\Users\\tmp\terminal-plus-internal-ui
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--verbose" "closure-util"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1
npm ERR! code ELIFECYCLE

npm ERR! closure-util@1.10.0 postinstall: `node ./bin/closure-util.js update`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the closure-util@1.10.0 postinstall script 'node ./bin/closure-util.js update'.
npm ERR! This is most likely a problem with the closure-util package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/closure-util.js update
npm ERR! You can get their info via:
npm ERR!     npm owner ls closure-util
npm ERR! There is likely additional logging output above.
npm verb exit [ 1, true ]
```

**Comment by harinigudipati** [comment]
My `.npmrc` file was correct but my `HTTP_PROXY` was wrong meaning that the npm was working but the node/get-down/request was failing.
